[package]
name = "tui_chat_server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version="1.0.219", features = ["derive"]}
serde_json = "1.0.140"
argon2 = "0.5.3"
rand_core = "0.9.3"
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio-native-tls", "chrono"] }
tokio = { version = "1.45.1", features = ["full"] }
