[package]
name = "tui_chat_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
argon2 = "0.5.3"
rand = "0.9.1"
serde = {version="1.0.219", features = ["derive"]}
serde_json = "1.0.140"
sqlx = "0.8.6"
tokio = { version = "1.45.1", features = ["full"] }
uuid = "1.17.0"
